/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

int main(void)
{
    printf("size of character data type: %u\n",sizeof(char));
    printf("size of short data type:     %u\n",sizeof(short));
    printf("size of integer data type:   %u\n",sizeof(int));
    printf("size of long data type:      %u\n",sizeof(long));
    printf("size of long long data type: %u\n",sizeof(long long));
    printf("size of double data type:    %u\n",sizeof(double));

	return 0;
}
