/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

void delay(int num);

int main(void)
{
	/* STM32F446RE Nucleo Board
	   LED connected on PA5
	 */

    uint32_t *pClkCtrlReg = (uint32_t*)0x40023830;
    uint32_t *pPortAModeReg = (uint32_t*)0x40020000;
    uint32_t *pPortAOutReg = (uint32_t*)0x40020014;

    //enable the clock for GPIOA peripheral
    *pClkCtrlReg  |=  (1<<0);

    // configure the mode I/O pin as Output
    // A. clear the 10th & 11h bit position
    *pPortAModeReg &= ~(3<<10);
    // B. make 10th bit position as 1(SET)
    *pPortAModeReg |= (1<<10);

    while(1){
    // set 5th bit of the output data register to make I/O pin-5 as HIGH
    *pPortAOutReg |= (1<<5);
    delay(100000);
    // reset 5th bit of the output data register to make I/O pin-5 as LOW
    *pPortAOutReg &= ~(1<<5);
    delay(100000);
    }
}

void delay(int num){
	for(int i=0; i<=num; i++);
}
