/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

int num1 = 1101;
int num2 = 2802;
int result = 0;

int main(void)
{
	result = num1 + num2;
	printf("Result = %d\n",result);
	return 0;

	/*
	 * using memory browser analyzing data
	 * 0x80000000 FLASH program memory starting address
	 * 0x20000000 SRAM data memory starting address
	 * view .elf file to copying data flash to data memory.
	 * Disassembly
	 * instruction level debugging
	 */



}
