/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

int main(void)
{
    uint32_t volatile *const pclkCntReg    = (uint32_t*)0x40023830;
    uint32_t volatile *const pPortDModeReg = (uint32_t*)0x40020C00;
    uint32_t volatile *const pPortDOutReg  = (uint32_t*)0x40020C14;

    uint32_t volatile *const pPortAModeReg = (uint32_t*)0x40020000;
    uint32_t const volatile *const pPortAInReg   = (uint32_t*)0x40020010;

    // clock Enable for GPIOD, GPIOA;
    *pclkCntReg |= (9<<0);

    // configure I/O pin As output GPIOD
    // A. clear bit for 26,27 & 30,31
    *pPortDModeReg &= ~(3<<26); //orange
    *pPortDModeReg &= ~(3<<30); //blue

    //B. set bit 01 for output
    *pPortDModeReg |=  (1<<26); //orange
    *pPortDModeReg |=  (1<<30);

    // configure I/O pin as input GPIOC
    //A. clear = set 00
    *pPortAModeReg &= ~(3<<0); //PA0

    while(1){

    	uint8_t pinstatus = (uint8_t)(*pPortAInReg & 0x1);

    	if(pinstatus){
    		// write 1 to output data
    		*pPortDOutReg |= (1<<13); //orange;
    		*pPortDOutReg |= (1<<15); //blue
    	}else{
    		// write 0 to output data
    		*pPortDOutReg &= ~(1<<13); //orange
        	*pPortDOutReg &= ~(1<<15); //blue
    	}
    }
}
