/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include<stdio.h>

int main(void){

	char msg1[] ="hello world";
	char *msg2 = "nilesh";

	printf("massage = %s\n",msg1);
	printf("address of a msg1 variable = %p\n",&msg1);  // both are same in sram
	printf("address of a msg1 variable = %p\n",msg1);

	printf("massage = %s\n",msg2);
	printf("address of a msg2 variable = %p\n",&msg2);   // sram
	printf("address of a msg2 variable = %p\n",msg2);    // data flash

	for(;;);
}
